version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MsSqlServer2019
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_01
    networks:
      - sql-net-1
    ports:
      - 1433:1433
    volumes:
      - C:/volumes/mssql_2019_data:/var/opt/mssql/data
networks:
  sql-net-1:
